services:
  documentserver:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    ports:
      - "6659:80"
    environment:
      - JWT_SECRET=your-secret-key-change-me
      - SECURE_LINK_SECRET=verysecretstring
      - HASH=0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
